//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Url2Ringtone.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Url2Ringtone.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add favourite.
        /// </summary>
        public static string AddFavourite {
            get {
                return ResourceManager.GetString("AddFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autoplay downloaded content.
        /// </summary>
        public static string AutoPlayHeader {
            get {
                return ResourceManager.GetString("AutoPlayHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        public static string BrowserBack {
            get {
                return ResourceManager.GetString("BrowserBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward.
        /// </summary>
        public static string BrowserForward {
            get {
                return ResourceManager.GetString("BrowserForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string BrowserRefresh {
            get {
                return ResourceManager.GetString("BrowserRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checking link....
        /// </summary>
        public static string CheckingLink {
            get {
                return ResourceManager.GetString("CheckingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check links.
        /// </summary>
        public static string CheckLinks {
            get {
                return ResourceManager.GetString("CheckLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear locally stored files.
        /// </summary>
        public static string ClearLocalFiles {
            get {
                return ResourceManager.GetString("ClearLocalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sure you wish to remove locally held mp3/wma files? this cannot be undone.\n\nthis will not clear the history.
        /// </summary>
        public static string ClearLocalFilesText {
            get {
                return ResourceManager.GetString("ClearLocalFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sure?.
        /// </summary>
        public static string ClearLocalFilesTitle {
            get {
                return ResourceManager.GetString("ClearLocalFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete these favourites?.
        /// </summary>
        public static string DeleteFavouritesText {
            get {
                return ResourceManager.GetString("DeleteFavouritesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you&apos;d like to delete your recently visited sites?.
        /// </summary>
        public static string DeleteHistoryText {
            get {
                return ResourceManager.GetString("DeleteHistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter display name here.
        /// </summary>
        public static string DisplayNameHint {
            get {
                return ResourceManager.GetString("DisplayNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t check links.
        /// </summary>
        public static string DontCheckLinks {
            get {
                return ResourceManager.GetString("DontCheckLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloading file....
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit favourite.
        /// </summary>
        public static string EditFavourite {
            get {
                return ResourceManager.GetString("EditFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email me.
        /// </summary>
        public static string EmailMe {
            get {
                return ResourceManager.GetString("EmailMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favourites.
        /// </summary>
        public static string Favourites {
            get {
                return ResourceManager.GetString("Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebTone Feedback.
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have found an audio file that you clicked on, would you like to download that file now?.
        /// </summary>
        public static string FileFoundText {
            get {
                return ResourceManager.GetString("FileFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio File Found.
        /// </summary>
        public static string FileFoundTitle {
            get {
                return ResourceManager.GetString("FileFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size too big, audio must be less than 1mb.
        /// </summary>
        public static string FileSizeError {
            get {
                return ResourceManager.GetString("FileSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file type isn&apos;t supported.
        /// </summary>
        public static string FileTypeError {
            get {
                return ResourceManager.GetString("FileTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t determine what sort of file this is, is it a WMA or MP3?.
        /// </summary>
        public static string FileTypeText {
            get {
                return ResourceManager.GetString("FileTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what file type?.
        /// </summary>
        public static string FileTypeTitle {
            get {
                return ResourceManager.GetString("FileTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics by .
        /// </summary>
        public static string GraphicsBy {
            get {
                return ResourceManager.GetString("GraphicsBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my site.
        /// </summary>
        public static string MySite {
            get {
                return ResourceManager.GetString("MySite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my twitter.
        /// </summary>
        public static string MyTwitter {
            get {
                return ResourceManager.GetString("MyTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ringtone name.
        /// </summary>
        public static string NameHint {
            get {
                return ResourceManager.GetString("NameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items in the history.
        /// </summary>
        public static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network connection available.
        /// </summary>
        public static string NoNetworkConnectionError {
            get {
                return ResourceManager.GetString("NoNetworkConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app also uses the brilliant NotificationBox by .
        /// </summary>
        public static string NotificationBoxText {
            get {
                return ResourceManager.GetString("NotificationBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like us to pause your music for you? It will start up when the ringtone isn&apos;t playing.\n\nIf you don&apos;t want to see this prompt again, you can turn it off in the settings..
        /// </summary>
        public static string PauseMusicText {
            get {
                return ResourceManager.GetString("PauseMusicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause music?.
        /// </summary>
        public static string PauseMusicTitle {
            get {
                return ResourceManager.GetString("PauseMusicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will pause any music you were listening to if turned on.
        /// </summary>
        public static string PauseNotification {
            get {
                return ResourceManager.GetString("PauseNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string PivotAbout {
            get {
                return ResourceManager.GetString("PivotAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to history.
        /// </summary>
        public static string PivotHistory {
            get {
                return ResourceManager.GetString("PivotHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ringtone.
        /// </summary>
        public static string PivotRingtone {
            get {
                return ResourceManager.GetString("PivotRingtone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate app.
        /// </summary>
        public static string RateApp {
            get {
                return ResourceManager.GetString("RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recent.
        /// </summary>
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the link for the mp3/wma file you want as the ringtone. It must be less than 1mb and the track less than 40 seconds. Once downloaded, give the ringtone a name, then add it to your list of ringtones..
        /// </summary>
        public static string RingtoneInstructions {
            get {
                return ResourceManager.GetString("RingtoneInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to denotes ringtone file is saved locally.
        /// </summary>
        public static string RingtoneKey {
            get {
                return ResourceManager.GetString("RingtoneKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ringtone name.
        /// </summary>
        public static string RingtoneName {
            get {
                return ResourceManager.GetString("RingtoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ringtone size: .
        /// </summary>
        public static string RingtoneSize {
            get {
                return ResourceManager.GetString("RingtoneSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save ringtone locally.
        /// </summary>
        public static string SaveRingtoneLocally {
            get {
                return ResourceManager.GetString("SaveRingtoneLocally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter url here.
        /// </summary>
        public static string UrlFavouriteHint {
            get {
                return ResourceManager.GetString("UrlFavouriteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter ringtone url.
        /// </summary>
        public static string UrlHint {
            get {
                return ResourceManager.GetString("UrlHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use &apos;smart&apos; browsing.
        /// </summary>
        public static string UseSmartBrowsing {
            get {
                return ResourceManager.GetString("UseSmartBrowsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
